apiVersion: v1
kind: Pod
metadata:
  name: multi-containers
  namespace: roboshop
  labels:
    name: multi-container
    project: roboshop
spec:
  containers:
  - name: nginx
    image: nginx
  - name: almalinux
    image: almalinux:9
    command: ["sleep", "100"]


==========================================

apiVersion: v1
kind: Namespace
metadata:
  name: roboshop
  labels:
    name: roboshop-multi
