apiVersion: v1
kind: pod
metadata:
  name: nginx
  namespace: roboshop
  labels:
    project: roboshop
    name: nginx
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80